name: Gaurav Manek
markdown: redcarpet
highlighter: pygments
description: "An online portfolio and website."
url: "http://www.gauravmanek.com"

source:      ./_content
destination: ./_site
plugins:     ./_plugins
layouts:     ./_layouts
include:     ['.htaccess']
exclude:     []

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "page"
      innavbar: false
  -
    scope:
      path: "/projects"
    values:
      layout: "post"
      category: "projects"

  -
    scope:
      path: "/blog"
    values:
      layout: "post"
      category: "blog"