name: Gaurav Manek
markdown: redcarpet
highlighter: rouge
description: "Online Portfolio and Website."
url: "http://gauravmanek.com"

source:      ./_content
destination: ./_site
plugins_dir: ./_plugins
layouts_dir: ./_layouts
include:     ['.htaccess']
exclude:     []
permalink: /:categories/:year/:title/

redcarpet:
  extensions: ["tables", "no_intra_emphasis", "smart"]

less:
  entrypoint: "css/main.less"

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "page"
      innavbar: false
      innavbar-order: 100
  -
    scope:
      path: "/projects"
    values:
      layout: "post"
      category: "projects"
  -
    scope:
      path: "/blog"
    values:
      layout: "post"
      category: "blog"
  -
    scope:
      path: "/research"
    values:
      layout: "post"
      category: "research"
